name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  create:
    tags: ["*"]

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis/redis-stack-server
        ports: ["6379:6379"]
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Hatch
        run: pip install --upgrade hatch

      - name: Run tests
        run: hatch run cov
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Build package
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags')
        run: hatch build

      - name: Publish package
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_KEY }}
