name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.11

    services:
      redis:
        image: redis/redis-stack-server
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Hatch
        run: pip install --upgrade hatch

      - name: Run tests
        run: hatch run cov
        env:
          REDIS_URL: redis://@redis:6379
          REDIS_OM_URL: redis://@redis:6379
